version: '3.8'

services:
  game-rating-app:
    build: .
    ports:
      - "8501:8501"
    volumes:
      - ./logs:/app/logs
      - ./data:/app/data
      - ./model:/app/model
    environment:
      - PYTHONPATH=/app
    restart: unless-stopped